// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! Generated request and response models declared under `celestial_bodies`.

#[allow(unused_imports)]
use super::*;
use serde::{Deserialize, Serialize};

/// A celestial body which can be either a planet or a satellite
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
#[non_exhaustive]
pub enum CelestialBody {
    #[serde(rename = "planet")]
    Planet(Planet),
    #[serde(rename = "satellite")]
    Satellite(Satellite),
    /// A variant not recognized by this version of the SDK, preserved verbatim.
    ///
    /// Match the specific variants first. Matching this one directly is an
    /// anti-pattern: that arm silently stops matching once a future SDK
    /// release adds the real variant.
    #[serde(untagged)]
    Unknown(serde_json::Value),
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SatelliteOrbit {
    /// The ID of the planet this satellite orbits
    #[serde(rename = "planetId", default, skip_serializing_if = "Option::is_none")]
    pub planet_id: Option<i64>,
    /// Orbital period in Earth days
    #[serde(
        rename = "orbitalPeriod",
        default,
        skip_serializing_if = "Option::is_none",
        serialize_with = "crate::number::option::serialize"
    )]
    pub orbital_period: Option<f64>,
    /// Average distance from the planet in kilometers
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        serialize_with = "crate::number::option::serialize"
    )]
    pub distance: Option<f64>,
}
